version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:vbb
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:vbb
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:vbb
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local