version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:vaa
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:vaa
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:vaa
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local